#! /bin/sh

# General configuration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Run keybinds daemon
	pgrep -x sxkd > /dev/null | sxhkd & 

# Fix Cursor
	xsetroot -cursor_name left_ptr

# Start X Wallpaper
	feh --bg-scale $HOME/Pictures/Wallpapers/totoro.jpg

# Polybar
	polybar -c .config/polybar/config

